### ISSUE TITLE
include tag is not supported

### ISSUE THREAD

**Issue by huluwa-dev** [laobie/FindViewByMe#14]
The plugin cannot find widgets in included layout.Please fix it.

**Comment by laobie** [comment]
OK, wait for a while.

**Comment by laobie** [comment]
include tag is supported all the time. What's wrong?

**Comment by vishalpatel1327** [comment]
yes, the same scenario happen with me 

`<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:scrollbars="none">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:padding="@dimen/margin_20">

        <include layout="@layout/include_card" />

        <Button
            android:id="@+id/btn_Reg_next"
            style="@style/Button"
            android:layout_marginTop="@dimen/margin_20"
            android:background="@drawable/btn_selector"
            android:gravity="center"
            android:text="@string/splash_reg"
            android:textColor="@color/white" />
    </LinearLayout>
</ScrollView>`




look into image
![screenshot from 2017-03-24 15-06-28](https://cloud.githubusercontent.com/assets/14329287/24288490/98a4c1d2-10a3-11e7-9f41-235f93f6ade0.png)

**Comment by laobie** [comment]
Please show me  the `include_card ` code.

**Comment by vishalpatel1327** [comment]
> 


<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.design.widget.TextInputLayout
        android:id="@+id/il_reg_card_holder_name"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <EditText
            android:id="@+id/edt_reg_card_holder_name"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:drawablePadding="@dimen/margin_10"
            android:hint="@string/card_holder_name"
            android:inputType="text"
            android:textColor="@color/text_color"
            android:textColorHint="@color/text_hintcolor"
            android:textSize="@dimen/textsize_normal"
            android:typeface="normal" />

    </android.support.design.widget.TextInputLayout>


    <android.support.design.widget.TextInputLayout
        android:id="@+id/il_reg_card_number"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.ridein.customer.Support.CreditCardValidation.EditCard
            android:id="@+id/edt_reg_card_number"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:drawablePadding="@dimen/margin_10"
            android:hint="@string/credit_card_number"
            android:inputType="text"
            android:textColor="@color/text_color"
            android:textColorHint="@color/text_hintcolor"
            android:textSize="@dimen/textsize_normal"
            android:typeface="normal" />

    </android.support.design.widget.TextInputLayout>




    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:padding="@dimen/margin_5">


        <android.support.design.widget.TextInputLayout
            android:id="@+id/il_reg_card_cardtype"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <Spinner
                android:id="@+id/sp_reg_card_cardtypr"
                android:layout_width="match_parent"
                android:layout_height="30dp" />
        </android.support.design.widget.TextInputLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="@dimen/border_line"
            android:background="@color/border"></LinearLayout>
    </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/margin_5"
        android:orientation="vertical"
        android:padding="@dimen/margin_5">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">


            <android.support.design.widget.TextInputLayout
                android:id="@+id/il_reg_card_cardtype_month"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_weight="1">


                <Spinner
                    android:id="@+id/sp_reg_card_month"
                    android:layout_width="match_parent"

                    android:layout_height="30dp" />
            </android.support.design.widget.TextInputLayout>

            <LinearLayout
                android:layout_width="@dimen/border_line"
                android:layout_height="match_parent"
                android:layout_marginBottom="5dp"
                android:background="@color/border"></LinearLayout>

            <android.support.design.widget.TextInputLayout
                android:id="@+id/il_reg_card_cardtype_year"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_weight="1">


                <Spinner
                    android:id="@+id/sp_reg_card_year"
                    android:layout_width="match_parent"

                    android:layout_height="30dp" />
            </android.support.design.widget.TextInputLayout>

        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="@dimen/border_line"
            android:background="@color/border"></LinearLayout>
    </LinearLayout>


    <android.support.design.widget.TextInputLayout
        android:id="@+id/il_reg_card_cvv"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <EditText
            android:id="@+id/edt_reg_card_cvv"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:drawablePadding="@dimen/margin_10"
            android:hint="@string/cvv"
            android:inputType="text"
            android:textColor="@color/text_color"
            android:textColorHint="@color/text_hintcolor"
            android:textSize="@dimen/textsize_normal"
            android:typeface="normal" />

    </android.support.design.widget.TextInputLayout>

</LinearLayout>

**Comment by laobie** [comment]
![image](https://cloud.githubusercontent.com/assets/7184320/24293785/68dc89e6-10ce-11e7-9ed5-db91e5baeab6.png)
Sorry I don't know why.

**Comment by laobie** [comment]
@vishalpatel1327 
Your `include_card` don't have a root tag?

**Comment by vishalpatelbacancy** [comment]
It have as a root Linear Layout but when i copy pest on Git comment remove automatically dont know why ?

**Comment by vishalpatel1327** [comment]
@laobie   is it possible that its effect on Latest Version for android studio 2.3?  In Ubuntu 16.04?

**Comment by huluwa-dev** [comment]
@vishalpatel1327 I don't think so, mine was on Mac.

**Comment by laobie** [comment]
@EricInCD You may need to fork this repo and debug on your machine to find why ...

**Comment by laobie** [comment]
@EricInCD `include` worked in xml file not in Java file.
I will fix the bug soon

**Comment by laobie** [comment]
@EricInCD @vishalpatel1327 1.3.7 fix this bug. Please update and check this.

**Comment by huluwa-dev** [comment]
I updated it, but I found that I cannot use it any more, it threw a NullPointerException.
<img width="364" alt="2017-04-04 11 38 45" src="https://cloud.githubusercontent.com/assets/4637964/24640676/811b92bc-192b-11e7-9d55-67998e5041fb.png">

**Comment by laobie** [comment]
@EricInCD give me detail error message if possible

**Comment by huluwa-dev** [comment]
Here it is.

null
java.lang.NullPointerException
	at com.jaeger.findviewbyme.util.ActionUtil.switchAddM(ActionUtil.java:39)
	at com.jaeger.findviewbyme.action.FindViewByMeXmlAction.actionPerformed(FindViewByMeXmlAction.java:51)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$2(ActionMenuItem.java:304)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:905)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:284)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:627)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by laobie** [comment]
OK, I will take a look

**Comment by laobie** [comment]
@EricInCD I can't reappear this bug, here is my QQ number: xxxxxxx, I will give you a test version to find what happened.

**Comment by huluwa-dev** [comment]
I didn't update it, I reinstalled it, so maybe you can do the same thing and try again.

**Comment by laobie** [comment]
@EricInCD  I reinstalled it too.

**Comment by laobie** [comment]
I tested on IDEA and Android Studio both. I can't find what cause this exception. May I can add some code to avoid null exception, but I guess you still can't use this plugin.

**Comment by huluwa-dev** [comment]
I reinstalled again, and got the same exception...
Can you send your test version to my email: lkfromcd@gmail.com?
I will tell you the result.

**Comment by laobie** [comment]
@EricInCD Gmail can't send email with .jar file. Can you spend some time fork this repository and debug on your machine to find problem?

**Comment by huluwa-dev** [comment]
Change the suffix, then you can send it.   (o゜▽゜)o☆[BINGO!]

**Comment by laobie** [comment]
@EricInCD email sent. If still can't work, I will never fix this, this waste my too much time.

**Comment by huluwa-dev** [comment]
呃。。。

**Comment by huluwa-dev** [comment]
Oh yeah, It works, bug fixed.

**Comment by huluwa-dev** [comment]
That's really odd...

**Comment by laobie** [comment]
@EricInCD `include` tag supported ?

**Comment by huluwa-dev** [comment]
There is a new bug. I can't find any views if I use the plugin in a java file, but it works in layout xml files.
<img width="593" alt="2017-04-06 12 30 47" src="https://cloud.githubusercontent.com/assets/4637964/24737991/20623bba-1ac5-11e7-8e46-2be9d2530465.png">
<img width="624" alt="2017-04-06 12 31 48" src="https://cloud.githubusercontent.com/assets/4637964/24737992/2064284e-1ac5-11e7-9e65-bc8ab16cbc7f.png">

**Comment by laobie** [comment]
@EricInCD Fork this repository, and debug on your machine. You can see this post -- [Android Studio插件开发实践\-\-从创建到发布 \- 简书](http://www.jianshu.com/p/f017097e4b26)

**Comment by huluwa-dev** [comment]
OK, I will take a try.

**Comment by huluwa-dev** [comment]
Please check you email, I've sent you the result.

**Comment by laobie** [comment]
I am so sorry. I still can't reappear this bug.
![image](https://cloud.githubusercontent.com/assets/7184320/24739740/11a767f2-1ad0-11e7-8fb2-1a8426f51426.png)

**Comment by laobie** [comment]
I hate open source.😒

**Comment by huluwa-dev** [comment]
Take it easy, man.
