### ISSUE TITLE
java/nio/charset/StandardCharsets

### ISSUE THREAD

**Issue by yemengsky** [laobie/FindViewByMe#2]
ava/nio/charset/StandardCharsets
java.lang.NoClassDefFoundError: java/nio/charset/StandardCharsets
    at ViewSaxHandler.createViewList(ViewSaxHandler.java:48)
    at FindViewByMeAction.getViewList(FindViewByMeAction.java:79)
    at FindViewByMeAction.actionPerformed(FindViewByMeAction.java:53)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:513)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
    at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
    at java.awt.Component.processMouseEvent(Component.java:6414)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
    at java.awt.Component.processEvent(Component.java:6179)
    at java.awt.Container.processEvent(Container.java:2084)
    at java.awt.Component.dispatchEventImpl(Component.java:4776)
    at java.awt.Container.dispatchEventImpl(Container.java:2142)
    at java.awt.Component.dispatchEvent(Component.java:4604)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
    at java.awt.Container.dispatchEventImpl(Container.java:2128)
    at java.awt.Window.dispatchEventImpl(Window.java:2492)
    at java.awt.Component.dispatchEvent(Component.java:4604)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:690)
    at java.awt.EventQueue$3.run(EventQueue.java:688)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: java.nio.charset.StandardCharsets PluginClassLoader[com.jaeger.findviewbyme, 1.2]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 47 more

**Comment by yemengsky** [comment]
> InputStream xmlStream = new ByteArrayInputStream(string.getBytes(StandardCharsets.UTF_8));

change to

> InputStream xmlStream = new ByteArrayInputStream(string.getBytes("UTF-8"));

**Comment by laobie** [comment]
ok 我看一下这个问题

**Comment by yemengsky** [comment]
要不我改改试试？

**Comment by laobie** [comment]
你改完测试下，没问题我就合并过来 : )

**Comment by yemengsky** [comment]
@laobie EmptyThrowable: Null child action in group XML Generate Actions () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=AutoFindView

**Comment by yemengsky** [comment]
目前又是这个错误，你之前有遇到过吗？

**Comment by laobie** [comment]
没有也= =

**Comment by yemengsky** [comment]
嗯，我改到明天中午12点，要是还改不好就麻烦你了。

**Comment by laobie** [comment]
不着急的，你先改着

**Comment by yemengsky** [comment]
@laobie 之前那个问题应该是没有在JDK1.6版本编译，要不你在合并之前验证一下？
http://stackoverflow.com/questions/25728962/intellij-plugin-development-pluginexception-cannot-create-class-action
